### ISSUE TITLE
Getting Trying to copy from a source that does not exist error on .gitignore file

### ISSUE THREAD

**Issue by eliprand** [owsas/generator-typescript-module#1]
Using yeoman and this generator for the first time. Just ran `npm i -g yeoman generator-typescript-module` on my mac. Running the `yo` command, selecting `Typescript Module` and filled out the various prompts.
I get: 
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/eliprandi/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/generators/app/typescript-module-template/.gitignore
    at EditionInterface.exports.copy (/Users/eliprandi/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at module.exports.writing (/Users/eliprandi/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/generators/app/index.js:48:13)
    at Object.<anonymous> (/Users/eliprandi/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/node_modules/yeoman-generator/lib/index.js:399:25)
    at /Users/eliprandi/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/eliprandi/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/eliprandi/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

I have verified and there is no `.gitignore` file there:
```
$ ll ~/.nvm/versions/node/v8.11.1/lib/node_modules/generator-typescript-module/generators/app/typescript-module-template/
total 440
drwxr-xr-x  14 eliprandi  staff     448 Sep 18 14:46 .
drwxr-xr-x   5 eliprandi  staff     160 Sep 18 14:46 ..
-rw-r--r--   1 eliprandi  staff      42 Oct 26  1985 .npmignore
drwxr-xr-x   3 eliprandi  staff      96 Sep 18 14:46 .vscode
-rw-r--r--   1 eliprandi  staff    1049 Oct 26  1985 README.md
-rw-r--r--   1 eliprandi  staff      27 Oct 26  1985 _config.yml
-rw-r--r--   1 eliprandi  staff  198119 Oct 26  1985 package-lock.json
-rw-r--r--   1 eliprandi  staff    1279 Oct 26  1985 package.json
drwxr-xr-x   3 eliprandi  staff      96 Sep 18 14:46 repo
drwxr-xr-x   4 eliprandi  staff     128 Sep 18 14:46 sh
drwxr-xr-x   3 eliprandi  staff      96 Sep 18 14:46 src
drwxr-xr-x   3 eliprandi  staff      96 Sep 18 14:46 test
-rw-r--r--   1 eliprandi  staff     261 Oct 26  1985 tsconfig.json
-rw-r--r--   1 eliprandi  staff     272 Oct 26  1985 tslint.json
```

I was reading online that `npm` will rename `.gitignore` to `.npmignore` on publish or something like that. Is there a workaround for this?

**Comment by jcguarinpenaranda** [comment]
Hello!! Thanks for reporting! I will check it up

**Comment by jcguarinpenaranda** [comment]
Thanks to @CaringIsCreepy, #2 should fix this problem!
